In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("raw_data.csv")
dataset

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [3]:
dataset.isnull()
dataset.isnull().sum()
dataset.dropna()

mean_age = dataset['age'].mean()
print(mean_age)

cleaned_data = dataset.copy()
#cleaned_data['age'] = cleaned_data['age'].ffill()
#cleaned_data['age'] = cleaned_data['age'].fillna(mean_age)
cleaned_data

32.75

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [12]:
# How to handle the duplicate 
dataset.duplicated()
dataset[['country', 'gender']].duplicated()
# dataset = dataset.drop_duplicates()
dataset.drop_duplicates(inplace=True)
dataset

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [21]:
dataset2 = dataset.copy()
dataset2['income'] = dataset2['income'].fillna(0)
dataset2
dataset2['income'] = dataset2['income'].astype('Int64')
dataset2

    id          name   age country   gender  income
0    1      John Doe  29.0     USA     Male   55000
2    2    Jane Smith   NaN  Canada   Female   62000
3    3          Alex   NaN     USA  Unknown   47000
4    4  Maria Garcia  34.0   Spain   Female       0
5    5        Li Wei  27.0   China     Male   51000
6    6           NaN  45.0   India   Female   73000
7    7    Ahmed Khan  38.0     NaN     Male   68000
8    8    Rachel Lee  29.0     USA   Female   62000
9    9   Carlos Ruiz   NaN  Mexico     Male   45000
10  10   Emily Davis  31.0     USA      NaN   58000

In [24]:
date_time = "2026-11-24"
print(type(date_time))
date_time = pd.to_datetime(date_time)
print(date_time)
print(type(date_time))

<class 'str'>
2026-11-24 00:00:00
<class 'pandas.Timestamp'>

In [30]:
dataset2['country'].str.lower()
dataset2['country'].str.upper()
dataset2['country'].str.capitalize()
dataset2['name'].str.strip(" ")
dataset2['country'].str.contains("ind" , case=False)

0     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
Name: country, dtype: bool

In [25]:
dataset2

    id          name   age country   gender  income
0    1      John Doe  29.0     USA     Male   55000
2    2    Jane Smith   NaN  Canada   Female   62000
3    3          Alex   NaN     USA  Unknown   47000
4    4  Maria Garcia  34.0   Spain   Female       0
5    5        Li Wei  27.0   China     Male   51000
6    6           NaN  45.0   India   Female   73000
7    7    Ahmed Khan  38.0     NaN     Male   68000
8    8    Rachel Lee  29.0     USA   Female   62000
9    9   Carlos Ruiz   NaN  Mexico     Male   45000
10  10   Emily Davis  31.0     USA      NaN   58000