In [138]:
import numpy as np
import pandas as pd

In [139]:
dataset = pd.read_csv("employee_dataset_60_rows.csv")
dataset_work = dataset.copy()

In [140]:
def tax(income):
    if income > 50000:
        tax = (income * 20)/100
    else :
        tax = (income * 10)/100
    return tax

dataset_work['tax'] = dataset_work['Salary'].apply(tax)

In [141]:
gender_map = {"Male" : "M" , 
              "Female" : "F",
              "Unknown" : "U"}

dataset_work['Gender'] = dataset_work['Gender'].map(gender_map)

In [142]:
dataset_work = dataset_work.drop(columns="tax")
dataset_work = dataset_work.assign(tax = dataset_work['Salary'] * 20 /100)

In [143]:
dataset_work = dataset_work.rename(columns={"tax" : "Tax"})
salary_sorted_data = dataset_work.sort_values("Salary")
salary_sorted_data.reset_index(drop=True)
salary_sorted_data['Ranking'] = salary_sorted_data['Performance_Rating'].rank(ascending=False)

In [144]:
salary_sorted_data.sort_values("Ranking")
salary_sorted_data = salary_sorted_data[['Name' , 'Age' , 'Gender' , 'Department' , 'Salary' , 'City' , 'Experience_Years' , 'Education', 'Performance_Rating' , 'Joining_Year' , 'Employment_Type' , 'Tax' , 'Ranking' , 'ID']]
salary_sorted_data

,Name,Age,Gender,Department,Salary,City,Experience_Years,Education,Performance_Rating,Joining_Year,Employment_Type,Tax,Ranking,ID
7,Hannah,26,F,Marketing,47000,Gurugram,15,PhD,4.8,1991,Part-Time,9400.0,6.0,8
2,Charlie,28,M,Finance,48000,Bengaluru,8,MBA,3.9,2004,Full-Time,9600.0,27.0,3
5,Frank,29,M,Finance,50000,Hyderabad,0,Master's,3.4,2020,Full-Time,10000.0,38.0,6
50,Adrian,24,M,Finance,51000,Delhi,0,MBA,3.7,2024,Full-Time,10200.0,31.5,51
34,Isaac,28,M,Finance,52200,Chennai,0,MBA,2.9,2020,Full-Time,10440.0,49.5,35
18,Sam,32,M,Finance,53400,Noida,4,MBA,4.7,2012,Full-Time,10680.0,8.5,19
52,Carter,38,M,HR,53600,Bengaluru,12,Bachelor's,2.5,1998,Full-Time,10720.0,59.0,53
36,Karan,42,M,HR,54800,Kolkata,16,Bachelor's,4.3,1990,Full-Time,10960.0,17.5,37
0,Alice,25,F,HR,55000,Delhi,0,Bachelor's,2.5,2026,Full-Time,11000.0,59.0,1
51,Bianca,31,F,Marketing,55300,Mumbai,8,PhD,4.4,2009,Part-Time,11060.0,15.5,52
20,Uma,46,F,HR,56000,Delhi,20,Bachelor's,3.5,1982,Full-Time,11200.0,35.5,21
35,Jasmine,35,F,Marketing,56500,Hyderabad,12,PhD,3.6,2001,Part-Time,11300.0,33.5,36
19,Tina,39,F,Marketing,57700,Jaipur,16,PhD,2.8,1993,Part-Time,11540.0,51.5,20
9,Julia,30,F,Finance,60000,Jaipur,2,Master's,3.6,2019,Full-Time,12000.0,33.5,10
54,Elijah,23,M,Finance,60200,Chennai,0,MBA,3.9,2025,Full-Time,12040.0,27.0,55
38,Manish,27,M,Finance,61400,Noida,3,MBA,3.1,2018,Full-Time,12280.0,45.5,39
22,Wendy,31,F,Finance,62600,Bengaluru,7,MBA,4.9,2010,Full-Time,12520.0,3.5,23
56,Gavin,37,M,HR,62800,Kolkata,15,Bachelor's,2.7,1996,Full-Time,12560.0,54.0,57
17,Rachel,25,F,IT,63100,Gurugram,0,Master's,4.0,2023,Full-Time,12620.0,24.5,18
40,Oscar,41,M,HR,64000,Delhi,19,Bachelor's,4.5,1988,Full-Time,12800.0,13.5,41
55,Farah,30,F,Marketing,64500,Hyderabad,3,PhD,4.6,2015,Part-Time,12900.0,11.0,56
4,Eva,38,F,IT,65000,Chennai,24,Bachelor's,2.7,1974,Full-Time,13000.0,54.0,5
24,Yara,45,F,HR,65200,Chennai,23,Bachelor's,3.7,1980,Full-Time,13040.0,31.5,25
39,Neha,34,F,Marketing,65700,Jaipur,7,PhD,3.8,2007,Part-Time,13140.0,29.5,40
23,Xavier,38,M,Marketing,66900,Pune,11,PhD,3.0,1999,Part-Time,13380.0,47.5,24
58,Jason,22,M,Finance,69400,Noida,0,MBA,4.1,2026,Full-Time,13880.0,22.0,59
53,Deepa,45,F,IT,69900,Pune,16,Master's,3.2,1987,Full-Time,13980.0,43.0,54
42,Rohan,26,M,Finance,70600,Bengaluru,0,MBA,3.3,2022,Full-Time,14120.0,40.5,43
37,Lily,49,F,IT,71100,Gurugram,20,Master's,5.0,1979,Full-Time,14220.0,1.5,38
26,Aaron,30,M,Finance,71800,Kolkata,2,MBA,2.5,2016,Full-Time,14360.0,59.0,27
1,Bob,32,M,IT,72000,Mumbai,4,Master's,3.2,2015,Full-Time,14400.0,43.0,2
21,Victor,24,M,IT,72300,Mumbai,0,Master's,4.2,2024,Full-Time,14460.0,19.5,22
10,Kevin,34,M,Finance,73000,Delhi,6,MBA,4.3,2008,Full-Time,14600.0,17.5,11
44,Thomas,40,M,HR,73200,Chennai,14,Bachelor's,4.7,1994,Full-Time,14640.0,8.5,45
59,Kiara,29,F,Marketing,73700,Jaipur,6,PhD,4.8,2013,Part-Time,14740.0,6.0,60
28,Caleb,44,M,HR,74400,Noida,18,Bachelor's,3.9,1986,Full-Time,14880.0,27.0,29
43,Sara,33,F,Marketing,74900,Pune,10,PhD,4.0,2005,Part-Time,14980.0,24.5,44
8,Ian,35,M,IT,75000,Noida,27,Bachelor's,2.9,1972,Full-Time,15000.0,49.5,9
12,Michael,48,M,HR,75600,Bengaluru,22,Bachelor's,3.1,1978,Full-Time,15120.0,45.5,13
27,Bella,37,F,Marketing,76100,Gurugram,14,PhD,3.2,1997,Part-Time,15220.0,43.0,28
11,Laura,41,F,Marketing,77300,Mumbai,18,PhD,5.0,1989,Part-Time,15460.0,1.5,12
57,Isha,44,F,IT,79100,Gurugram,19,Master's,3.4,1985,Full-Time,15820.0,38.0,58
46,Vikram,25,M,Finance,79800,Kolkata,1,MBA,3.5,2022,Full-Time,15960.0,35.5,47
41,Pooja,48,F,IT,80300,Mumbai,23,Master's,2.6,1977,Full-Time,16060.0,56.5,42
30,Ethan,29,M,Finance,81000,Delhi,5,MBA,2.7,2014,Full-Time,16200.0,54.0,31
25,Zach,23,M,IT,81500,Hyderabad,0,Master's,4.4,2025,Full-Time,16300.0,15.5,26
6,Grace,41,F,HR,82000,Kolkata,11,MBA,4.1,2002,Full-Time,16400.0,22.0,7
14,Oliver,33,M,Finance,82200,Chennai,9,MBA,4.5,2006,Full-Time,16440.0,13.5,15
48,Yusuf,39,M,HR,82400,Noida,17,Bachelor's,4.9,1992,Full-Time,16480.0,3.5,49
32,George,43,M,HR,83600,Bengaluru,21,Bachelor's,4.1,1984,Full-Time,16720.0,22.0,33
47,Willow,32,F,Marketing,84100,Gurugram,5,PhD,4.2,2011,Part-Time,16820.0,19.5,48
16,Quentin,47,M,HR,84800,Kolkata,25,Bachelor's,3.3,1976,Full-Time,16960.0,40.5,17
31,Fiona,36,F,Marketing,85300,Mumbai,9,PhD,3.4,2003,Part-Time,17060.0,38.0,32
15,Priya,40,F,Marketing,86500,Hyderabad,13,PhD,2.6,1995,Part-Time,17300.0,56.5,16
45,Urvi,47,F,IT,89500,Hyderabad,18,Master's,2.8,1983,Full-Time,17900.0,51.5,46
29,Diana,22,F,IT,90700,Jaipur,0,Master's,4.6,2026,Full-Time,18140.0,11.0,30
3,David,45,M,Marketing,91000,Pune,20,PhD,4.6,1985,Part-Time,18200.0,11.0,4
13,Nora,26,F,IT,91900,Pune,0,Master's,3.8,2022,Full-Time,18380.0,29.5,14
49,Zoe,46,F,IT,98700,Jaipur,21,Master's,3.0,1981,Full-Time,19740.0,47.5,50
33,Hazel,50,F,IT,99900,Pune,25,Master's,4.8,1973,Full-Time,19980.0,6.0,34

In [145]:
salary_sorted_data

,Name,Age,Gender,Department,Salary,City,Experience_Years,Education,Performance_Rating,Joining_Year,Employment_Type,Tax,Ranking,ID
7,Hannah,26,F,Marketing,47000,Gurugram,15,PhD,4.8,1991,Part-Time,9400.0,6.0,8
2,Charlie,28,M,Finance,48000,Bengaluru,8,MBA,3.9,2004,Full-Time,9600.0,27.0,3
5,Frank,29,M,Finance,50000,Hyderabad,0,Master's,3.4,2020,Full-Time,10000.0,38.0,6
50,Adrian,24,M,Finance,51000,Delhi,0,MBA,3.7,2024,Full-Time,10200.0,31.5,51
34,Isaac,28,M,Finance,52200,Chennai,0,MBA,2.9,2020,Full-Time,10440.0,49.5,35
18,Sam,32,M,Finance,53400,Noida,4,MBA,4.7,2012,Full-Time,10680.0,8.5,19
52,Carter,38,M,HR,53600,Bengaluru,12,Bachelor's,2.5,1998,Full-Time,10720.0,59.0,53
36,Karan,42,M,HR,54800,Kolkata,16,Bachelor's,4.3,1990,Full-Time,10960.0,17.5,37
0,Alice,25,F,HR,55000,Delhi,0,Bachelor's,2.5,2026,Full-Time,11000.0,59.0,1
51,Bianca,31,F,Marketing,55300,Mumbai,8,PhD,4.4,2009,Part-Time,11060.0,15.5,52
20,Uma,46,F,HR,56000,Delhi,20,Bachelor's,3.5,1982,Full-Time,11200.0,35.5,21
35,Jasmine,35,F,Marketing,56500,Hyderabad,12,PhD,3.6,2001,Part-Time,11300.0,33.5,36
19,Tina,39,F,Marketing,57700,Jaipur,16,PhD,2.8,1993,Part-Time,11540.0,51.5,20
9,Julia,30,F,Finance,60000,Jaipur,2,Master's,3.6,2019,Full-Time,12000.0,33.5,10
54,Elijah,23,M,Finance,60200,Chennai,0,MBA,3.9,2025,Full-Time,12040.0,27.0,55
38,Manish,27,M,Finance,61400,Noida,3,MBA,3.1,2018,Full-Time,12280.0,45.5,39
22,Wendy,31,F,Finance,62600,Bengaluru,7,MBA,4.9,2010,Full-Time,12520.0,3.5,23
56,Gavin,37,M,HR,62800,Kolkata,15,Bachelor's,2.7,1996,Full-Time,12560.0,54.0,57
17,Rachel,25,F,IT,63100,Gurugram,0,Master's,4.0,2023,Full-Time,12620.0,24.5,18
40,Oscar,41,M,HR,64000,Delhi,19,Bachelor's,4.5,1988,Full-Time,12800.0,13.5,41
55,Farah,30,F,Marketing,64500,Hyderabad,3,PhD,4.6,2015,Part-Time,12900.0,11.0,56
4,Eva,38,F,IT,65000,Chennai,24,Bachelor's,2.7,1974,Full-Time,13000.0,54.0,5
24,Yara,45,F,HR,65200,Chennai,23,Bachelor's,3.7,1980,Full-Time,13040.0,31.5,25
39,Neha,34,F,Marketing,65700,Jaipur,7,PhD,3.8,2007,Part-Time,13140.0,29.5,40
23,Xavier,38,M,Marketing,66900,Pune,11,PhD,3.0,1999,Part-Time,13380.0,47.5,24
58,Jason,22,M,Finance,69400,Noida,0,MBA,4.1,2026,Full-Time,13880.0,22.0,59
53,Deepa,45,F,IT,69900,Pune,16,Master's,3.2,1987,Full-Time,13980.0,43.0,54
42,Rohan,26,M,Finance,70600,Bengaluru,0,MBA,3.3,2022,Full-Time,14120.0,40.5,43
37,Lily,49,F,IT,71100,Gurugram,20,Master's,5.0,1979,Full-Time,14220.0,1.5,38
26,Aaron,30,M,Finance,71800,Kolkata,2,MBA,2.5,2016,Full-Time,14360.0,59.0,27
1,Bob,32,M,IT,72000,Mumbai,4,Master's,3.2,2015,Full-Time,14400.0,43.0,2
21,Victor,24,M,IT,72300,Mumbai,0,Master's,4.2,2024,Full-Time,14460.0,19.5,22
10,Kevin,34,M,Finance,73000,Delhi,6,MBA,4.3,2008,Full-Time,14600.0,17.5,11
44,Thomas,40,M,HR,73200,Chennai,14,Bachelor's,4.7,1994,Full-Time,14640.0,8.5,45
59,Kiara,29,F,Marketing,73700,Jaipur,6,PhD,4.8,2013,Part-Time,14740.0,6.0,60
28,Caleb,44,M,HR,74400,Noida,18,Bachelor's,3.9,1986,Full-Time,14880.0,27.0,29
43,Sara,33,F,Marketing,74900,Pune,10,PhD,4.0,2005,Part-Time,14980.0,24.5,44
8,Ian,35,M,IT,75000,Noida,27,Bachelor's,2.9,1972,Full-Time,15000.0,49.5,9
12,Michael,48,M,HR,75600,Bengaluru,22,Bachelor's,3.1,1978,Full-Time,15120.0,45.5,13
27,Bella,37,F,Marketing,76100,Gurugram,14,PhD,3.2,1997,Part-Time,15220.0,43.0,28
11,Laura,41,F,Marketing,77300,Mumbai,18,PhD,5.0,1989,Part-Time,15460.0,1.5,12
57,Isha,44,F,IT,79100,Gurugram,19,Master's,3.4,1985,Full-Time,15820.0,38.0,58
46,Vikram,25,M,Finance,79800,Kolkata,1,MBA,3.5,2022,Full-Time,15960.0,35.5,47
41,Pooja,48,F,IT,80300,Mumbai,23,Master's,2.6,1977,Full-Time,16060.0,56.5,42
30,Ethan,29,M,Finance,81000,Delhi,5,MBA,2.7,2014,Full-Time,16200.0,54.0,31
25,Zach,23,M,IT,81500,Hyderabad,0,Master's,4.4,2025,Full-Time,16300.0,15.5,26
6,Grace,41,F,HR,82000,Kolkata,11,MBA,4.1,2002,Full-Time,16400.0,22.0,7
14,Oliver,33,M,Finance,82200,Chennai,9,MBA,4.5,2006,Full-Time,16440.0,13.5,15
48,Yusuf,39,M,HR,82400,Noida,17,Bachelor's,4.9,1992,Full-Time,16480.0,3.5,49
32,George,43,M,HR,83600,Bengaluru,21,Bachelor's,4.1,1984,Full-Time,16720.0,22.0,33
47,Willow,32,F,Marketing,84100,Gurugram,5,PhD,4.2,2011,Part-Time,16820.0,19.5,48
16,Quentin,47,M,HR,84800,Kolkata,25,Bachelor's,3.3,1976,Full-Time,16960.0,40.5,17
31,Fiona,36,F,Marketing,85300,Mumbai,9,PhD,3.4,2003,Part-Time,17060.0,38.0,32
15,Priya,40,F,Marketing,86500,Hyderabad,13,PhD,2.6,1995,Part-Time,17300.0,56.5,16
45,Urvi,47,F,IT,89500,Hyderabad,18,Master's,2.8,1983,Full-Time,17900.0,51.5,46
29,Diana,22,F,IT,90700,Jaipur,0,Master's,4.6,2026,Full-Time,18140.0,11.0,30
3,David,45,M,Marketing,91000,Pune,20,PhD,4.6,1985,Part-Time,18200.0,11.0,4
13,Nora,26,F,IT,91900,Pune,0,Master's,3.8,2022,Full-Time,18380.0,29.5,14
49,Zoe,46,F,IT,98700,Jaipur,21,Master's,3.0,1981,Full-Time,19740.0,47.5,50
33,Hazel,50,F,IT,99900,Pune,25,Master's,4.8,1973,Full-Time,19980.0,6.0,34