In [67]:
import numpy as np
import pandas as pd

In [68]:
netflix_dataset = pd.read_csv("netflix_titles.csv")

In [69]:
print(f"The number of rows are :->  {netflix_dataset.shape[0]} ")
print(f"The number of columns are :->  {netflix_dataset.shape[1]}")
print(f"The names of the columns are :-> {netflix_dataset.columns} ")
print(f"The data types are :->  {netflix_dataset.dtypes}")
netflix_dataset.head()
netflix_dataset.tail()
print(netflix_dataset.isnull().sum())
print(netflix_dataset.nunique())
print(netflix_dataset.duplicated().sum())
print(netflix_dataset.describe())

The number of rows are :->  8807
The number of columns are :->  12
The names of the columns are :-> Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')
The data types are :->  show_id           str
type              str
title             str
director          str
cast              str
country           str
date_added        str
release_year    int64
rating            str
duration          str
listed_in         str
description       str
dtype: object
show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64
show_id         8807
type               2
title           8807
director        4528
cast            7692
country          748
date_added      1767
release_year      74
rating            17
duration         220
listed_in        514
description     8775
dtype: int64
0
       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [70]:
netflix_dataset_copy =  netflix_dataset.copy()
netflix_dataset_copy.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [71]:
netflix_dataset_copy['director'] = netflix_dataset['director'].fillna("Unknown")
netflix_dataset_copy['cast'] = netflix_dataset['cast'].fillna("Unknown")
netflix_dataset_copy['country'] = netflix_dataset['country'].fillna("Unknown")
netflix_dataset_copy['date_added'] = netflix_dataset['date_added'].fillna(0)
netflix_dataset_copy['duration'] = netflix_dataset['duration'].fillna(0)
netflix_dataset_copy['rating'] = netflix_dataset['rating'].fillna(0)
netflix_dataset_copy.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [72]:
# title
# director
# country
# rating
# listed_in
netflix_dataset_copy['type'] = netflix_dataset_copy['type'].str.lower()
netflix_dataset_copy['title'] = netflix_dataset_copy['title'].str.lower()
netflix_dataset_copy['director'] = netflix_dataset_copy['director'].str.lower()
netflix_dataset_copy['country'] = netflix_dataset_copy['country'].str.lower()
netflix_dataset_copy['rating'] = netflix_dataset_copy['rating'].str.upper()
netflix_dataset_copy['listed_in'] = netflix_dataset_copy['listed_in'].str.lower()
netflix_dataset_copy

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,movie,dick johnson is dead,kirsten johnson,Unknown,united states,"September 25, 2021",2020,PG-13,90 min,documentaries,"As her father nears the end of his life, filmm..."
1,s2,tv show,blood & water,unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",south africa,"September 24, 2021",2021,TV-MA,2 Seasons,"international tv shows, tv dramas, tv mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,tv show,ganglands,julien leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",unknown,"September 24, 2021",2021,TV-MA,1 Season,"crime tv shows, international tv shows, tv act...",To protect his family from a powerful drug lor...
3,s4,tv show,jailbirds new orleans,unknown,Unknown,unknown,"September 24, 2021",2021,TV-MA,1 Season,"docuseries, reality tv","Feuds, flirtations and toilet talk go down amo..."
4,s5,tv show,kota factory,unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",india,"September 24, 2021",2021,TV-MA,2 Seasons,"international tv shows, romantic tv shows, tv ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,movie,zodiac,david fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",united states,"November 20, 2019",2007,R,158 min,"cult movies, dramas, thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,tv show,zombie dumb,unknown,Unknown,unknown,"July 1, 2019",2018,TV-Y7,2 Seasons,"kids' tv, korean tv shows, tv comedies","While living alone in a spooky town, a young g..."
8804,s8805,movie,zombieland,ruben fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",united states,"November 1, 2019",2009,R,88 min,"comedies, horror movies",Looking to survive in a world taken over by zo...
8805,s8806,movie,zoom,peter hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",united states,"January 11, 2020",2006,PG,88 min,"children & family movies, comedies","Dragged from civilian life, a former superhero..."
8806,s8807,movie,zubaan,mozez singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",india,"March 2, 2019",2015,TV-14,111 min,"dramas, international movies, music & musicals",A scrappy but poor boy worms his way into a ty...

In [96]:
title_length_tv = 0 
description_length = 0
title_length_tv = (len(netflix_dataset_copy.query("type == 'tv show'")['title']).sum())/2676
print(title_length_tv)
netflix_dataset_copy.query("type == 'movie'")['title'].sum()

AttributeError: 'int' object has no attribute 'sum'

In [74]:
netflix_dataset_copy

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,movie,dick johnson is dead,kirsten johnson,Unknown,united states,"September 25, 2021",2020,PG-13,90 min,documentaries,"As her father nears the end of his life, filmm..."
1,s2,tv show,blood & water,unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",south africa,"September 24, 2021",2021,TV-MA,2 Seasons,"international tv shows, tv dramas, tv mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,tv show,ganglands,julien leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",unknown,"September 24, 2021",2021,TV-MA,1 Season,"crime tv shows, international tv shows, tv act...",To protect his family from a powerful drug lor...
3,s4,tv show,jailbirds new orleans,unknown,Unknown,unknown,"September 24, 2021",2021,TV-MA,1 Season,"docuseries, reality tv","Feuds, flirtations and toilet talk go down amo..."
4,s5,tv show,kota factory,unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",india,"September 24, 2021",2021,TV-MA,2 Seasons,"international tv shows, romantic tv shows, tv ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,movie,zodiac,david fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",united states,"November 20, 2019",2007,R,158 min,"cult movies, dramas, thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,tv show,zombie dumb,unknown,Unknown,unknown,"July 1, 2019",2018,TV-Y7,2 Seasons,"kids' tv, korean tv shows, tv comedies","While living alone in a spooky town, a young g..."
8804,s8805,movie,zombieland,ruben fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",united states,"November 1, 2019",2009,R,88 min,"comedies, horror movies",Looking to survive in a world taken over by zo...
8805,s8806,movie,zoom,peter hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",united states,"January 11, 2020",2006,PG,88 min,"children & family movies, comedies","Dragged from civilian life, a former superhero..."
8806,s8807,movie,zubaan,mozez singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",india,"March 2, 2019",2015,TV-14,111 min,"dramas, international movies, music & musicals",A scrappy but poor boy worms his way into a ty...