In [2]:
import numpy as np
import pandas as pd

In [3]:
info = {
    "Name" : ["Rahul" , "Dravid" , "Hritik"],
    "Marks" : [80,67,90]
}
info_dataframe = pd.DataFrame(info)
info_dataframe

     Name  Marks
0   Rahul     80
1  Dravid     67
2  Hritik     90

In [4]:
info_series = pd.Series(info["Marks"])
info_series

0    80
1    67
2    90
dtype: int64

In [5]:
info_series2 = pd.Series(info["Marks"] , index=["Hello" , "Hi" ,"Bye"])
info_series2

Hello    80
Hi       67
Bye      90
dtype: int64

In [6]:
info_series2["Hello"] = 99
print(info_series2)
changed_info_series2 = info_series2.drop("Hello")
print(changed_info_series2)
print(info_series2)

Hello    99
Hi       67
Bye      90
dtype: int64
Hi     67
Bye    90
dtype: int64
Hello    99
Hi       67
Bye      90
dtype: int64

In [7]:
info_array = pd.DataFrame([["Bob" , 63 ] , ["Alice" , 90], ["Chris" , 87]] , columns=["Name" , "Marks"])
info_array

    Name  Marks
0    Bob     63
1  Alice     90
2  Chris     87

In [8]:
employee_data = pd.read_csv("employee_data.csv")
employee_data

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [19]:
# print(employee_data.head())
# print(employee_data.tail())
# print(employee_data.info())
# print(employee_data.shape)
# print(employee_data.describe())
print(employee_data.columns)
print(employee_data.nunique())

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='str')
ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64